INSERT INTO menu (menu_id, name, category_id, price, image)
VALUES
-- อาหารจานเดียว (category_id = 1)
(1, N'ข้าวสวย', 1, 10.00, 'src-front/img-oneDishMeal/kaosuay.png'),
(2, N'ผัดกะเพราหมูสับ', 1, 45.00, 'src-front/img-oneDishMeal/padkrapaomoosap.avif'),
(3, N'ผัดกะเพราหมูเด้ง', 1, 55.00, 'src-front/img-oneDishMeal/moodeng.jpg'),
(4, N'ผัดกะเพราปลาหมึก', 1, 70.00, 'src-front/img-oneDishMeal/kapowpamuk.webp'),
(5, N'ผัดกะเพราหมูกรอบ', 1, 60.00, 'src-front/img-oneDishMeal/kapowmukob.webp'),
(6, N'ผัดกะเพราไก่', 1, 50.00, 'src-front/img-oneDishMeal/kapowgai.webp'),
(7, N'ผัดกะเพรากุ้ง', 1, 65.00, 'src-front/img-oneDishMeal/kapowkung.jpg'),
(8, N'พริกแกงหมู', 1, 45.00, 'src-front/img-oneDishMeal/prikkang moo.jpg'),
(9, N'พริกแกงไก่', 1, 50.00, 'src-front/img-oneDishMeal/prikkang gai.webp'),
(10, N'พริกแกงเนื้อ', 1, 60.00, 'src-front/img-oneDishMeal/prikkang beef.webp'),
(11, N'คะน้าหมูกรอบ', 1, 60.00, 'src-front/img-oneDishMeal/kanamukob.jpg'),
(12, N'ผัดแขนงหมูกรอบ', 1, 55.00, 'src-front/img-oneDishMeal/kanangmukob.jpg'),
(13, N'ผัดผักบุ้ง', 1, 45.00, 'src-front/img-oneDishMeal/padpakbung.jpeg'),
(14, N'ผัดผักรวม', 1, 50.00, 'src-front/img-oneDishMeal/padpakruam.jpg'),
(15, N'ผัดผงกะหรี่ปลาหมึก', 1, 70.00, 'src-front/img-oneDishMeal/pongkaree pamuk.jpg'),
(16, N'ผัดผงกะหรี่กุ้ง', 1, 65.00, 'src-front/img-oneDishMeal/pongkaree kung.jpg'),
(17, N'ผัดผงกะหรี่ไก่', 1, 55.00, 'src-front/img-oneDishMeal/pongkaree gai.jpg'),
(18, N'หมูผัดกระเทียม', 1, 45.00, 'src-front/img-oneDishMeal/moo kateam.jpg'),
(19, N'ไก่ผัดกระเทียม', 1, 50.00, 'src-front/img-oneDishMeal/gai kateam.jpg'),
(20, N'หมูผัดน้ำมันหอย', 1, 45.00, 'src-front/img-oneDishMeal/moo nammanhoi.jpg'),
(21, N'หมูผัดพริกหยวก', 1, 50.00, 'src-front/img-oneDishMeal/moo pikyuak.jpg'),
(22, N'ไก่ผัดพริกหยวก', 1, 55.00, 'src-front/img-oneDishMeal/gai prikyuak.jpg'),
(23, N'หมูผัดเปรี้ยวหวาน', 1, 55.00, 'src-front/img-oneDishMeal/preawwanmoo.jpg'),
(24, N'ปลาผัดเปรี้ยวหวาน', 1, 70.00, 'src-front/img-oneDishMeal/preawwanfish.webp'),
(25, N'ขี้เมาหมู', 1, 50.00, 'src-front/img-oneDishMeal/keemao moo.jpg'),
(26, N'ขี้เมาไก่', 1, 55.00, 'src-front/img-oneDishMeal/keemao gai.jpg'),
(27, N'ขี้เมาเนื้อ', 1, 65.00, 'src-front/img-oneDishMeal/keemao beef.jpg'),
(28, N'ขี้เมาทะเล', 1, 70.00, 'src-front/img-oneDishMeal/keemao tale.png'),
(29, N'สปาเก็ตตี้ขี้เมา', 1, 65.00, 'src-front/img-oneDishMeal/spa keemao.jpg'),
(30, N'ข้าวไข่เจียว', 1, 35.00, 'src-front/img-oneDishMeal/kaokaijeaw.jpg'),
(31, N'ไข่เจียวกุ้ง', 1, 50.00, 'src-front/img-oneDishMeal/kaijeaw kung.jpg'),
(32, N'ไข่เจียวหมู', 1, 45.00, 'src-front/img-oneDishMeal/kaijeaw moosub.jpg'),
(33, N'ไข่เจียวปู', 1, 80.00, 'src-front/img-oneDishMeal/kaijeaw poo.jpg'),
(34, N'ข้าวผัดหมู', 1, 50.00, 'src-front/img-oneDishMeal/kaopad moo.jpg'),
(35, N'ข้าวผัดกุ้ง', 1, 65.00, 'src-front/img-oneDishMeal/kaopadkung.png'),
(36, N'ข้าวผัดทะเล', 1, 70.00, 'src-front/img-oneDishMeal/kaopad tale.jpg'),
(37, N'ข้าวผัดปลากระป๋อง', 1, 50.00, 'src-front/img-oneDishMeal/kaopad papong.webp'),
(38, N'ผัดซีอิ๊วหมู', 1, 55.00, 'src-front/img-oneDishMeal/padsiew moo.jpg'),
(39, N'ราดหน้าหมู', 1, 55.00, 'src-front/img-oneDishMeal/radna moo.webp'),
(40, N'ผัดไทยกุ้ง', 1, 50.00, 'src-front/img-oneDishMeal/padthai kungsod.webp'),
(41, N'ต้มจืดหมู', 1, 50.00, 'src-front/img-oneDishMeal/tomjuad moo.webp'),
(42, N'สุกี้น้ำหมู', 1, 55.00, 'src-front/img-oneDishMeal/sukinam moo.jpg'),
(43, N'สุกี้น้ำทะเล', 1, 70.00, 'src-front/img-oneDishMeal/sukinam tale.jpg'),
(44, N'สุกี้แห้งหมู', 1, 55.00, 'src-front/img-oneDishMeal/suki hang moo.jpg'),
(45, N'ยำหมูยอ', 1, 50.00, 'src-front/img-oneDishMeal/yum moo yor.jpg'),
(46, N'ยำวุ้นเส้นทะเล', 1, 70.00, 'src-front/img-oneDishMeal/yum wonsen tale.jpg'),
(47, N'ยำปลากระป๋อง', 1, 50.00, 'src-front/img-oneDishMeal/yum pakapong.jpg'),
(48, N'ข้าวต้มกุ้ง', 1, 65.00, 'src-front/img-oneDishMeal/kaotom kung.jpg'),
(49, N'ข้าวต้มหมู', 1, 45.00, 'src-front/img-oneDishMeal/kaotom moosab.jpg'),
(50, N'ข้าวต้มปลา', 1, 60.00, 'src-front/img-oneDishMeal/kaotom pla.jpg'),

-- เครื่องดื่ม (category_id = 2)
(51, N'น้ำเปล่า', 2, 10.00, 'src-front/img-beverage/namthip.jpeg'),
(52, N'เป๊ปซี่', 2, 25.00, 'src-front/img-beverage/pepsi.webp'),
(53, N'สตรอเบอร์รี่โซดา', 2, 35.00, 'src-front/img-beverage/strawberry_lime_soda.jpg'),
(54, N'บลูฮาวายโซดา', 2, 35.00, 'src-front/img-beverage/blue_hawaii.jpg'),
(55, N'แดงโซดา', 2, 35.00, 'src-front/img-beverage/red_soda.jpg'),
(56, N'ชาพีช', 2, 35.00, 'src-front/img-beverage/peach_tea.jpg'),
(57, N'ลิ้นจี่', 2, 35.00, 'src-front/img-beverage/lychee.webp'),
(58, N'ชามะนาว', 2, 35.00, 'src-front/img-beverage/lemon_tea.jpg'),
(59, N'ชาแอปเปิ้ล', 2, 35.00, 'src-front/img-beverage/apple_tea.avif'),
(60, N'ชาไทย', 2, 35.00, 'src-front/img-beverage/thai_tea.jpg'),
(61, N'ชาเขียว', 2, 40.00, 'src-front/img-beverage/green_tea.webp'),
(62, N'โอเลี้ยง', 2, 40.00, 'src-front/img-beverage/oleang.webp'),
(63, N'โอวัลติน', 2, 35.00, 'src-front/img-beverage/ovaltine.jpg'),
(64, N'กาแฟโบราณ', 2, 40.00, 'src-front/img-beverage/coffee.jpg'),

-- ของทานเล่น / ของหวาน (category_id = 3)
(65, N'นักเก็ต', 3, 40.00, 'src-front/img-dessert/nugget.webp'),
(66, N'ไก่ป๊อป', 3, 40.00, 'src-front/img-dessert/pop-chicken.jpg'),
(67, N'เฟรนช์ฟรายส์', 3, 40.00, 'src-front/img-dessert/french-fries.jpg'),
(68, N'ชีสบอล', 3, 50.00, 'src-front/img-dessert/cheese-ball.jpg'),
(69, N'ไส้กรอกทอด', 3, 40.00, 'src-front/img-dessert/sausages.jpg'),
(70, N'มันบดอบชีส', 3, 65.00, 'src-front/img-dessert/potato.webp'),
(71, N'ปีกไก่ทอด', 3, 55.00, 'src-front/img-dessert/chicken-wings.jpg'),
(72, N'เกี๊ยวซ่า', 3, 60.00, 'src-front/img-dessert/dumpling.jpg'),
(73, N'ปังปิ้ง', 3, 50.00, 'src-front/img-dessert/bread.jpg'),
(74, N'ไอศกรีม', 3, 45.00, 'src-front/img-dessert/ice-cream.jpg'),
(75, N'เค้กลาวา', 3, 70.00, 'src-front/img-dessert/choclava.jpg'),
(76, N'เค้กหน้านิ่ม', 3, 75.00, 'src-front/img-dessert/cake.jpg'),
(77, N'บัวลอย', 3, 65.00, 'src-front/img-dessert/coconut-cream.webp'),
(78, N'ปาท่องโก๋', 3, 65.00, 'src-front/img-dessert/patonggo.png');
